rows = [
    ("AC", "Acre", "Assembleia Legislativa do Estado do Acre"),
    ("AL", "Alagoas", "Assembleia Legislativa do Estado de Alagoas"),
    ("AM", "Amazonas", "Assembleia Legislativa do Estado do Amazonas"),
    ("AP", "Amapá", "Assembleia Legislativa do Estado do Amapá"),
    ("BA", "Bahia", "Assembleia Legislativa do Estado da Bahia"),
    ("CE", "Ceará", "Assembleia Legislativa do Estado do Ceará"),
    ("ES", "Espírito Santo", "Assembleia Legislativa do Estado do Espírito Santo"),
    ("GO", "Goiás", "Assembleia Legislativa do Estado de Goiás"),
    ("MA", "Maranhão", "Assembleia Legislativa do Estado do Maranhão"),
    ("MG", "Minas Gerais", "Assembleia Legislativa do Estado de Minas Gerais"),
    ("MS", "Mato Grosso do Sul", "Assembleia Legislativa do Estado de Mato Grosso do Sul"),
    ("MT", "Mato Grosso", "Assembleia Legislativa do Estado de Mato Grosso"),
    ("PA", "Pará", "Assembleia Legislativa do Estado do Pará"),
    ("PB", "Paraíba", "Assembleia Legislativa do Estado da Paraíba"),
    ("PE", "Pernambuco", "Assembleia Legislativa do Estado de Pernambuco"),
    ("PI", "Piauí", "Assembleia Legislativa do Estado do Piauí"),
    ("PR", "Paraná", "Assembleia Legislativa do Estado do Paraná"),
    ("RJ", "Rio de Janeiro", "Assembleia Legislativa do Estado do Rio de Janeiro"),
    ("RN", "Rio Grande do Norte", "Assembleia Legislativa do Estado do Rio Grande do Norte"),
    ("RO", "Rondônia", "Assembleia Legislativa do Estado de Rondônia"),
    ("RR", "Roraima", "Assembleia Legislativa do Estado de Roraima"),
    ("RS", "Rio Grande do Sul", "Assembleia Legislativa do Estado do Rio Grande do Sul"),
    ("SC", "Santa Catarina", "Assembleia Legislativa do Estado de Santa Catarina"),
    ("SE", "Sergipe", "Assembleia Legislativa do Estado de Sergipe"),
    ("SP", "São Paulo", "Assembleia Legislativa do Estado de São Paulo"),
    ("TO", "Tocantins", "Assembleia Legislativa do Estado do Tocantins"),
]